[project]
name = "lili-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "partial>=1.0",
    "tqdm>=4.67.1",
    "xlsxwriter>=3.2.2",
]
